" jzone1366

" UI Layout
set number		          " Show line numbers
set relativenumber	          " Show relative numbers
set showcmd		          " Show command in bottom bar
set cursorline	                  " Highlight current line
set showmatch		          " Highlight matching parenthesis
filetype plugin indent on         " Set filetype indentation detection
set wildmenu		          " visual autocomplete for command menu
set lazyredraw		          " redraw only when we need to
set laststatus=2
set noshowmode                    " turn off mode since it now shows in airline
runtime macros/matchit.vim
set autoindent			  " Turn on auto indentation
set backspace=indent,eol,start 	  " Proper backspace behavior.
" }}}

" Searching {{{
set ignorecase		          " ignore case when searching
set incsearch		          " search as characters are entered
set hlsearch		          " highligh all matches
" }}}

" Folding {{{
set foldenable		          " enable folding
set foldlevelstart=10	          " open most folds by default
set foldnestmax=10	          " 10 nested fold max
set foldmethod=indent	          " fold based on indent level
" }}}

" Finding Files {{{
set path+=**                      " Search down into sub folders
set wildignore+=*/node_modules/*  " Ignore node_modules
" }}}

" File Browsing {{{
let g:netrw_altv=1                " open splits to the right
" }}}

" Commands {{{
command! MakeTags !ctags -R --exclude=node_modules .
command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update()
command! PackClean  packadd minpac | source $MYVIMRC | call minpac#clean()
" }}}

" MINPAC {{{
if exists('*minpac#init')
  " minpac is loaded.
  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})
  "call minpac#add('morhetz/gruvbox')
  call minpac#add('tomasr/molokai')
  call minpac#add('tpope/vim-surround')
  call minpac#add('tpope/vim-sleuth')
  call minpac#add('sheerun/vim-polyglot')
  call minpac#add('vim-airline/vim-airline')
  call minpac#add('vim-airline/vim-airline-themes')
  call minpac#add('fatih/vim-go', { 'do': ':GoInstallBinaries' })
endif
" }}}

" Global {{{
let g:airline_theme='tomorrow'
let g:rehash256 = 1
" }}}

" Color {{{
syntax enable		          " enable syntax processing
"colorscheme gruvbox
"colorscheme molokai
colorscheme tomorrowNightBright
" }}}
